spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://viamedisdev.b2clogin.com/viamedisdev.onmicrosoft.com/b2c_1_susi/discovery/v2.0/keys"
  mvc:
    log-request-details: true

logging:
  level:
    root: debug
